// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const LOCAL_ADMIN_AUTH_KEY = 'holyfaith-admin-auth';
const LOCAL_DATA_PREFIX = 'holyfaith-local-data';
const STAFF_ACCESS_KEY = import.meta.env.VITE_STAFF_ACCESS_KEY || process.env.STAFF_ACCESS_KEY || '52005';

function getLocalTableKey(table: string): string {
  return `${LOCAL_DATA_PREFIX}:${table}`;
}

function readLocalTable(table: string): any[] {
  if (typeof window === 'undefined') return [];
  const raw = window.localStorage.getItem(getLocalTableKey(table));
  if (!raw) return [];
  try {
    return JSON.parse(raw) as any[];
  } catch {
    return [];
  }
}

function writeLocalTable(table: string, rows: any[]) {
  if (typeof window === 'undefined') return;
  window.localStorage.setItem(getLocalTableKey(table), JSON.stringify(rows));
}

function createLocalId(): string {
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
    return crypto.randomUUID();
  }
  return `${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

function createLocalQueryBuilder(table: string) {
  const state: {
    operation: 'select' | 'insert' | 'update' | 'delete';
    payload?: Record<string, unknown>;
    filters: Array<{ column: string; value: unknown }>;
    orderBy?: { column: string; ascending: boolean };
  } = {
    operation: 'select',
    filters: [],
  };

  const builder = {
    select: () => {
      state.operation = 'select';
      return builder;
    },
    order: (column: string, options?: { ascending?: boolean }) => {
      state.orderBy = { column, ascending: options?.ascending ?? true };
      return builder;
    },
    eq: (column: string, value: unknown) => {
      state.filters.push({ column, value });
      return builder;
    },
    insert: (payload: Record<string, unknown>) => {
      state.operation = 'insert';
      state.payload = payload;
      return builder;
    },
    update: (payload: Record<string, unknown>) => {
      state.operation = 'update';
      state.payload = payload;
      return builder;
    },
    delete: () => {
      state.operation = 'delete';
      return builder;
    },
    then: (resolve: (value: { data: any; error: null }) => void, reject: (reason?: unknown) => void) => {
      const execute = async () => {
        const rows = readLocalTable(table);

        if (state.operation === 'insert') {
          const created = {
            id: createLocalId(),
            created_at: new Date().toISOString(),
            ...(state.payload ?? {}),
          };
          if (table === 'admission_enquiries' && !('status' in created)) {
            created.status = 'new';
          }
          const nextRows = [created, ...rows];
          writeLocalTable(table, nextRows);
          return { data: created, error: null };
        }

        let filtered = rows;
        for (const filter of state.filters) {
          filtered = filtered.filter((row) => row[filter.column] === filter.value);
        }

        if (state.operation === 'delete') {
          const nextRows = rows.filter((row) => !state.filters.some((filter) => row[filter.column] === filter.value));
          writeLocalTable(table, nextRows);
          return { data: null, error: null };
        }

        if (state.operation === 'update') {
          const nextRows = rows.map((row) => {
            const matches = state.filters.every((filter) => row[filter.column] === filter.value);
            return matches ? { ...row, ...(state.payload ?? {}) } : row;
          });
          writeLocalTable(table, nextRows);
          filtered = nextRows.filter((row) => state.filters.every((filter) => row[filter.column] === filter.value));
        }

        if (state.orderBy) {
          filtered = [...filtered].sort((a, b) => {
            const left = a[state.orderBy!.column];
            const right = b[state.orderBy!.column];
            if (left === right) return 0;
            const result = left > right ? 1 : -1;
            return state.orderBy!.ascending ? result : -result;
          });
        }

        return { data: filtered, error: null };
      };

      return execute().then(resolve, reject);
    },
  } as any;

  return builder;
}

export function setLocalAdminSession(email: string) {
  if (typeof window === 'undefined') return;
  const payload = {
    email,
    role: 'staff',
    authenticatedAt: new Date().toISOString(),
  };
  window.localStorage.setItem(LOCAL_ADMIN_AUTH_KEY, JSON.stringify(payload));
}

export function getLocalAdminSession() {
  if (typeof window === 'undefined') return null;
  const stored = window.localStorage.getItem(LOCAL_ADMIN_AUTH_KEY);
  if (!stored) return null;

  try {
    const parsed = JSON.parse(stored);
    if (parsed && typeof parsed === 'object' && typeof parsed.email === 'string') {
      return { email: parsed.email, role: parsed.role ?? 'staff' };
    }
  } catch {
    // fall back to the legacy plain-string session
  }

  return stored ? { email: stored, role: 'staff' } : null;
}

export function clearLocalAdminSession() {
  if (typeof window === 'undefined') return;
  window.localStorage.removeItem(LOCAL_ADMIN_AUTH_KEY);
}

export function authenticateStaff(email: string, accessKey: string) {
  const trimmedEmail = email.trim();
  if (!trimmedEmail) {
    return { success: false as const, error: 'Please enter your staff email.' };
  }

  if (accessKey !== STAFF_ACCESS_KEY) {
    return { success: false as const, error: 'Invalid staff access key.' };
  }

  setLocalAdminSession(trimmedEmail);
  return { success: true as const };
}

function createFallbackSupabaseClient() {
  return {
    from: (table: string) => createLocalQueryBuilder(table),
    auth: {
      getUser: async () => {
        const session = getLocalAdminSession();
        return { data: { user: session ? { email: session.email } : null }, error: null };
      },
      getSession: async () => {
        const session = getLocalAdminSession();
        return { data: { session: session ? { access_token: 'local-staff-session' } : null }, error: null };
      },
      signInWithPassword: async ({ email, password }: { email: string; password: string }) => {
        const result = authenticateStaff(email, password);
        if (result.success) {
          return { data: { user: { email }, session: { access_token: 'local-staff-session' } }, error: null };
        }
        return { data: { user: null, session: null }, error: { message: result.error } };
      },
      signUp: async () => ({ data: { user: null, session: null }, error: { message: 'Staff sign-up is disabled. Ask the school admin for the access key.' } }),
      signOut: async () => {
        clearLocalAdminSession();
        return { error: null };
      },
      resetPasswordForEmail: async () => ({ error: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => undefined } } }),
    },
  } as any;
}

function createSupabaseClient() {
  // This project uses a staff-only local access flow for the dashboard, so the
  // fallback client is used to ensure the admissions form and staff portal work
  // reliably both locally and when opened from the network.
  return createFallbackSupabaseClient();
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from '@/integrations/supabase/client';
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

